"""Vector database and persistence module for DocuMind."""

from backend.src.vectordb.vector_store import (
    get_collection,
    add_chunks,
    get_document,
    document_exists,
    register_document,
    list_documents,
    remove_document,
    clear_all_documents,
    get_document_chunks,
    get_all_chunks,
    get_adjacent_chunks,
    query_vector_store,
)
from backend.src.vectordb.database import (
    get_db_connection,
    init_db,
    insert_document,
    update_document_status,
    get_document_by_id,
    get_document_by_name,
    list_all_documents,
    set_document_archived,
    delete_document_permanently,
    create_chat_session,
    update_chat_session,
    get_chat_session,
    list_chat_sessions,
    set_chat_session_archived,
    delete_chat_session_permanently,
    insert_chat_message,
    get_session_messages,
)

__all__ = [
    "get_collection",
    "add_chunks",
    "get_document",
    "document_exists",
    "register_document",
    "list_documents",
    "remove_document",
    "clear_all_documents",
    "get_document_chunks",
    "get_all_chunks",
    "get_adjacent_chunks",
    "query_vector_store",
    "get_db_connection",
    "init_db",
    "insert_document",
    "update_document_status",
    "get_document_by_id",
    "get_document_by_name",
    "list_all_documents",
    "set_document_archived",
    "delete_document_permanently",
    "create_chat_session",
    "update_chat_session",
    "get_chat_session",
    "list_chat_sessions",
    "set_chat_session_archived",
    "delete_chat_session_permanently",
    "insert_chat_message",
    "get_session_messages",
]
