/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1c1a",
        "card-surface": "#EFE9DE",
        "inverse-on-surface": "#f2f1ed",
        "surface-container-low": "#f4f4f0",
        "background": "#faf9f5",
        "surface-bright": "#faf9f5",
        "inverse-primary": "#ffb59d",
        "secondary": "#5f5e5d",
        "outline": "#87736d",
        "secondary-fixed-dim": "#c9c6c4",
        "on-primary-container": "#fffbff",
        "on-error": "#ffffff",
        "secondary-fixed": "#e5e2e0",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#5f5c53",
        "on-tertiary-fixed": "#1d1b15",
        "error": "#ba1a1a",
        "surface-container-highest": "#e3e2df",
        "tertiary-fixed": "#e8e2d7",
        "muted-text": "#6C6A64",
        "surface-variant": "#e3e2df",
        "inverse-surface": "#2f312e",
        "surface-container": "#efeeea",
        "tertiary-container": "#78746b",
        "on-surface-variant": "#54433e",
        "on-background": "#1b1c1a",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#1c1c1a",
        "on-tertiary-container": "#fffbff",
        "coral-accent": "#CC785C",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbd0",
        "on-tertiary": "#ffffff",
        "primary-container": "#ad5f45",
        "primary-fixed-dim": "#ffb59d",
        "surface-container-high": "#e9e8e4",
        "on-primary-fixed": "#390c00",
        "on-primary-fixed-variant": "#75331c",
        "surface-tint": "#924a31",
        "on-secondary-fixed-variant": "#474745",
        "surface": "#faf9f5",
        "on-secondary-container": "#636261",
        "surface-dim": "#dbdad6",
        "tertiary-fixed-dim": "#cbc6bb",
        "on-secondary": "#ffffff",
        "canvas": "#FAF9F5",
        "outline-variant": "#dac1ba",
        "on-tertiary-fixed-variant": "#49473f",
        "secondary-container": "#e2dfdd",
        "primary": "#8f482f",
        "body-text": "#3D3D3A",
        "evidence-bg": "#181715",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "search-height": "70px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "content-max-width": "960px",
        "sidebar-width": "280px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ['"Source Serif 4"', "serif"],
        "headline-lg": ['"Source Serif 4"', "serif"],
        "headline-lg-mobile": ['"Source Serif 4"', "serif"],
        "headline-md": ['"Source Serif 4"', "serif"],
        "cormorant": ['"Cormorant Garamond"', "serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [forms, containerQueries],
};
